const state = { network: null, tools: null, screen: 'Dashboard', logs: [], projects: [] };
const nav = ['Dashboard','Auto Discovery','Manual Target','Network Pentest','Web Pentest','Ethical Hacking','Evidence','Reports','Projects','Settings'];
const $ = s => document.querySelector(s);
function log(message) { state.logs.unshift(`[${new Date().toLocaleTimeString()}] ${message}`); render(); }
function esc(x='') { return String(x).replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }
function api(path, options) { return fetch(path, options).then(r => r.json()); }
function current() { return state.network?.active; }
function card(label, value) { return `<div class="card"><small>${label}</small><div class="value">${esc(value || '—')}</div></div>`; }
function layout(content) { document.querySelector('#app').innerHTML = `<div class="shell"><aside class="side"><div class="brand">CYBERTEST</div><div class="by">BY GABRIEL HUERTAS<br>INTERNAL SECURITY PLATFORM</div><nav class="nav">${nav.map(x => `<button class="${state.screen===x?'active':''}" data-nav="${x}">${x}</button>`).join('')}</nav></aside><main>${content}</main></div>`; document.querySelectorAll('[data-nav]').forEach(b => b.onclick=()=>{state.screen=b.dataset.nav;render()}); }
function header(title, caption='AUTHORIZED INTERNAL ASSESSMENT') { return `<div class="head"><div><div class="eyebrow">${caption}</div><h1>${title}</h1></div><div class="status"><i class="dot"></i>LOCAL MODE</div></div>`; }
function dashboard() { const n=current(); return `${header('Dashboard')}<div class="grid">${card('Local IP',n?.ip)}${card('Network',n?.cidr)}${card('Interface',n?.name)}${card('Gateway','Detected at assessment start')}</div><div class="cols"><section class="panel"><h2>Current position</h2>${n ? `<table><tr><th>IP</th><td>${esc(n.ip)}</td></tr><tr><th>Netmask</th><td>${esc(n.netmask)}</td></tr><tr><th>MAC</th><td>${esc(n.mac)}</td></tr><tr><th>Host</th><td>${esc(state.network.hostname)}</td></tr></table>` : '<p>Loading network information…</p>'}<div class="actions" style="margin-top:15px"><button data-go="Auto Discovery">START AUTO DISCOVERY</button><button data-go="Manual Target">MANUAL TARGET</button></div></section><section class="panel"><h2>Assessment statistics</h2><div class="severity"><span class="sev critical">CRITICAL 0</span><span class="sev high">HIGH 0</span><span class="sev medium">MEDIUM 0</span><span class="sev low">LOW 0</span></div><p class="notice">No scan results are fabricated. Statistics update only from recorded assessment output.</p></section></div>${logPanel()}`; }
function logPanel(){return `<section class="panel"><h2>Activity log</h2><div class="log">${state.logs.map(esc).join('\n')||'Waiting for an assessment action.'}</div></section>`}
function autoDiscovery(){const n=current();return `${header('Auto Discovery')}<section class="panel"><h2>Local segment</h2><div class="grid">${card('Interface',n?.name)}${card('Local IP',n?.ip)}${card('Netmask',n?.netmask)}${card('CIDR',n?.cidr)}</div><div class="notice">Routed/reachable networks are informational. They are never scanned until explicitly entered as an assessment scope.</div><div class="actions"><button id="discover">START HOST DISCOVERY</button><button data-go="Manual Target">CHANGE SCOPE</button></div></section>${scopeForm(n?.cidr || '')}${logPanel()}`}
function scopeForm(defaultTarget=''){return `<section class="panel"><h2>Assessment scope</h2><label class="label">Target — CIDR, IP, hostname, or approved URL host</label><input id="target" value="${esc(defaultTarget)}" placeholder="192.168.10.0/24"><label class="label">Scan profile</label><select id="profile"><option value="standard">Standard scan (default)</option><option value="quick">Quick scan</option><option value="deep">Deep scan — safe Nmap scripts only</option></select><label><input type="checkbox" id="authorized" style="width:auto"> I confirm I am authorized to assess this explicit target.</label><div class="actions"><button id="scan">START ASSESSMENT</button></div><div id="scan-result"></div></section>`}
function manual(){return `${header('Manual Target')}<section class="panel"><h2>Define an authorized scope</h2><p>Enter only assets you are authorized to assess. Scope confirmation is required before any scanner is invoked.</p>${scopeForm()}</section>${logPanel()}`}
function toolsView(){const t=state.tools||{}; return `${header('Settings')}<section class="panel"><h2>Tool detection</h2><table><tr><th>Tool</th><th>Status</th><th>Resolved path</th></tr>${[['nmap','Nmap'],['nuclei','Nuclei'],['msfconsole','Metasploit Framework']].map(([id,name])=>`<tr><td>${name}</td><td>${t[id]?.installed?'<span class="sev low">INSTALLED</span>':'<span class="sev high">NOT FOUND</span>'}</td><td>${esc(t[id]?.path||'Configure via PATH')}</td></tr>`).join('')}</table><button id="check-tools" style="margin-top:14px">CHECK TOOLS</button><p class="notice">External tools are optional. A missing tool is reported clearly and does not close the application.</p></section>`}
function projects(){return `${header('Projects')}<section class="panel"><h2>Saved assessments</h2>${state.projects.length?`<table><tr><th>Project</th><th>Scope</th><th>Created</th></tr>${state.projects.map(p=>`<tr><td>${esc(p.name||'Untitled assessment')}</td><td>${esc(p.target||'—')}</td><td>${new Date(p.createdAt).toLocaleString()}</td></tr>`).join('')}</table>`:'<p>No projects have been saved yet.</p>'}</section>`}
function generic(){const labels={ 'Network Pentest':'Discovery → Enumeration → Scan → Assessment → Evidence → Report','Web Pentest':'Authorized HTTP/TLS review and evidence collection','Ethical Hacking':'Safe validation only; no destructive payloads or automatic exploitation.','Evidence':'Attach scanner output, screenshots, requests, responses and validation notes to a finding.','Reports':'Generate reports after findings and evidence are recorded.'};return `${header(state.screen)}<section class="panel"><h2>${labels[state.screen]}</h2><p>This module is intentionally gated until a scoped assessment is created. Results must originate from actual tooling; CYBERTEST does not invent hosts, CVEs, findings, or evidence.</p><button data-go="Manual Target">CREATE ASSESSMENT SCOPE</button></section>`}
function render(){const views={Dashboard:dashboard,'Auto Discovery':autoDiscovery,'Manual Target':manual,Settings:toolsView,Projects:projects};layout((views[state.screen]||generic)()); wire();}
function wire(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.go;render()});$('#check-tools')?.addEventListener('click',async()=>{state.tools=await api('/api/tools');log('Tool availability checked.');});$('#discover')?.addEventListener('click',()=>{log('Host discovery requires an explicit confirmed scope.');state.screen='Manual Target';render()});$('#scan')?.addEventListener('click',async()=>{const target=$('#target').value.trim(), authorized=$('#authorized').checked, profile=$('#profile').value;if(!authorized){$('#scan-result').innerHTML='<div class="notice">Confirmation of authorization is required before scanning.</div>';return}log(`Starting ${profile} scan for approved scope: ${target}`);const result=await api('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target,profile})});if(!result.ok){$('#scan-result').innerHTML=`<div class="notice">${esc(result.message||result.error||'Scan failed')}</div>`;log(`Scan unavailable: ${result.message||result.error}`);return}await api('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:`Assessment ${target}`,target,profile,rawNmapXml:result.output})});state.projects=await api('/api/projects');$('#scan-result').innerHTML='<div class="status"><i class="dot"></i>Scan completed and project saved. Raw Nmap XML is retained locally.</div>';log('Nmap completed; project saved locally.');});}
async function boot(){state.network=await api('/api/network');state.tools=await api('/api/tools');state.projects=await api('/api/projects');log(`Active interface detected: ${current()?.name||'none'}`)}boot();
